async function enviarScript(scriptText) {
  const lines = scriptText
    .split(/[\n\t]+/)
    .map((line) => line.trim())
    .filter((line) => line);
  (main = document.querySelector("#main")), (textarea = main.querySelector(`div[contenteditable="true"]`));

  if (!textarea) throw new Error("No hay una conversación abierta");

  for (const line of lines) {
    console.log(line);

    textarea.focus();
    document.execCommand("insertText", false, line);
    textarea.dispatchEvent(new Event("change", { bubbles: true }));

    setTimeout(() => {
      (main.querySelector(`[data-testid="send"]`) || main.querySelector(`[data-icon="send"]`)).click();
    }, 100);

    if (lines.indexOf(line) !== lines.length - 1) await new Promise((resolve) => setTimeout(resolve, 250));
  }

  return lines.length;
}

enviarScript(`
  \`Initializing script...\`
  \`fetching data...\`
  \`fetching data completed.\`
  \`fetching location...\`
  \`fetching location...\`
  \`fetching location completed.\`
  \`fetching members data...\`
  \`downloading data...\`
  \`decoding encryption...\`
  \`encryption key found.\`
  \`accessing secure server...\`
  \`bypassing firewall...\`
  \`firewall bypassed.\`
  \`injecting script...\`
  \`script injection successful.\`
  \`scanning network...\`
  \`network scan in progress...\`
  \`scanning for vulnerabilities...\`
  \`vulnerabilities detected.\`
  \`exploiting vulnerabilities...\`
  \`exploitation successful.\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`retrieving files...\`
  \`files retrieved.\`
  \`compiling reports...\`
  \`report compilation completed.\`
  \`clearing logs...\`
  \`logs cleared.\`
  \`connection terminated.\`
  `)
  .then((e) => console.log(`Código finalizado, ${e} mensajes enviados`))
  .catch(console.error);
